name: carla_conf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - tensorflow-gpu=2.2.0
  - numpy=1.19.5
  - pip
  - pip:
    - -r file:requirements.txt


